//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoulMatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerDb
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string CNIC { get; set; }
        public int ContactNo { get; set; }
        public string Adress { get; set; }
    }
}
