//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoulMatch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoulMatchEntities : DbContext
    {
        public SoulMatchEntities()
            : base("name=SoulMatchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BrokerDb> BrokerDbs { get; set; }
        public virtual DbSet<RegisteredUserDb> RegisteredUserDbs { get; set; }
        public virtual DbSet<UserDb> UserDbs { get; set; }
    }
}
