//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class broker
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string CNIC { get; set; }
        public string City { get; set; }
        public string Contact_No { get; set; }
        public string Email { get; set; }
        public int BrokerID { get; set; }
        public string Code { get; set; }
    }
}
