//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registered_users
    {
        public int UserID { get; set; }
        public string Image { get; set; }
        public string Fullname { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int? Age { get; set; }
        public string CNIC { get; set; }
        public string Adress { get; set; }
        public string Contact_no { get; set; }
        public string Email { get; set; }
        public int? Salary { get; set; }
        public string Gender { get; set; }
        public string Religion { get; set; }
        public string Cast { get; set; }
        public string Profession { get; set; }
        public string Account_no { get; set; }
        public string City { get; set; }
    }
}
