//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public int ID { get; set; }
        public string sender { get; set; }
        public string receiver { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
