//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterationLoginOfUser.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class user
    {
        public int UserID { get; set; }
        public string Image { get; set; }
        public HttpPostedFileBase Imagefile { get; set; }
        [DisplayName("Full Name")]
        [Required]

        public string Fullname { get; set; }
        [DisplayName("Username")]
        [Required]
        public string Username { get; set; }
        [DisplayName("Password")]

        [Required(AllowEmptyStrings = false, ErrorMessage = "This field is required")]
        [DataType(DataType.Password)]
        [MinLength(4, ErrorMessage = "minimum 4 characters required")]
        public string Password { get; set; }
        [DisplayName("Confirm Password")]

        [Required(AllowEmptyStrings = false, ErrorMessage = "This field is required")]
        [DataType(DataType.Password)]
        [MinLength(4, ErrorMessage = "minimum 4 characters required")]
        public string ConfirmPassword { get; set; }
        
        [Required(AllowEmptyStrings = false, ErrorMessage = "This field is required")]
        public int? Age { get; set; }
        
        [DisplayName("CNIC")]


        [Required(AllowEmptyStrings = true, ErrorMessage = "This field is required")]
        public int? CNIC { get; set; }
        [Required]
        [DataType(DataType.MultilineText)]
        public string Address { get; set; }
        [DisplayName("Contact No")]

        [Required]
        [DataType(DataType.PhoneNumber)]
        public int? Contact_no { get; set; }
        [DisplayName("Email Address")]

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        
        [Required(AllowEmptyStrings = true, ErrorMessage = "This field is required")]
        public int? Salary { get; set; }
        [Required]
        public string Gender { get; set; }
        [Required]
        public string Religion { get; set; }
        [Required]
        public string Caste { get; set; }
        [Required]
        public string Profession { get; set; }
        
        [DisplayName("Account No")]
        [Required]
        public int? Account_no { get; set; }
    }
}
