//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoulMatch.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class RegisteredUserDb
    {
        public int UserId { get; set; }
        public string Fulname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public int Contact_No { get; set; }
        public string Religion { get; set; }
        public string Cast { get; set; }
        public string City { get; set; }
        public string Adress { get; set; }
        public int CNIC { get; set; }
        public string Profession { get; set; }
        public int Salary { get; set; }
        public int Account_No { get; set; }
        public string Image { get; set; }
    }
}
